using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ManolyWarehouse.Infrastructure.Persistence;

#nullable disable

namespace ManolyWarehouse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709090350_AddActivityLogs")]
    public partial class AddActivityLogs : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Append-only audit log. IF NOT EXISTS keeps this safe against the
            // messy migration history in this project (partial applies, manual rows).
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "ActivityLogs" (
                    "Id"                integer GENERATED BY DEFAULT AS IDENTITY,
                    "Area"              character varying(20)  NOT NULL,
                    "Action"            character varying(500) NOT NULL,
                    "PerformedByUserId" character varying(450) NOT NULL,
                    "PerformedByName"   character varying(100) NOT NULL,
                    "PerformedByRole"   character varying(20)  NOT NULL,
                    "CreatedAt"         timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_CreatedAt"
                    ON "ActivityLogs" ("CreatedAt");

                CREATE INDEX IF NOT EXISTS "IX_ActivityLogs_Area"
                    ON "ActivityLogs" ("Area");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "ActivityLogs";""");
        }
    }
}
